# Generated by Django 2.1 on 2018-10-05 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('time', models.DateTimeField()),
            ],
            options={
                'db_table': 'appointment',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('doc_name', models.CharField(max_length=45)),
                ('hospital', models.CharField(max_length=45)),
                ('speciality', models.CharField(max_length=45)),
                ('working_hours', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'doctor',
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('username', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'login',
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('record_id', models.IntegerField(primary_key=True, serialize=False)),
                ('symptoms', models.CharField(max_length=200)),
                ('medicines', models.CharField(max_length=100)),
                ('appointments', models.CharField(max_length=200)),
                ('blogs', models.CharField(max_length=500)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='marsmdwebsite.Doctor')),
            ],
            options={
                'db_table': 'medical_record',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=45)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'patient',
            },
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='marsmdwebsite.Patient'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='marsmdwebsite.Doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='marsmdwebsite.Patient'),
        ),
    ]
